project:
  type: website
  output-dir: docs
  resources:
    - pdfs/**
    - notesimages/**

website:
  title: "Molecular Biology"
  navbar:
    left: []
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    highlight-style:
      light: github
      dark: dracula
    code-copy: true
    code-overflow: wrap
    grid:
      body-width: 1100px
      gutter-width: 1rem
    css: styles/site.css
