project:
  type: website
  output-dir: docs
  resources:
    - pdfs/**
    - notesimages/**

website:
  title: "Molecular Biology"
  navbar:
    left: []
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    mainfont: "Inter"
    monofont: "Menlo"
    highlight-style:
      dark: dracula
      light: github
    code-copy: true
    code-overflow: wrap
    grid:
      body-width: 1100px
      gutter-width: 1rem
    css:
      - styles/fonts.css
      - styles/styles.css
